--01
SELECT JOB_ID ,
  SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID LIKE '%_REP'
ORDER BY SUM(SALARY);

SELECT
  JOB_ID,
  SUM(SALARY)
FROM
  EMPLOYEES
WHERE
  JOB_ID NOT LIKE '%_REP'
GROUP BY
  JOB_ID
HAVING
  SUM(SALARY)> 13000
ORDER BY
  SUM(SALARY);
  
SELECT
  EMPLOYEE_ID ,
  COMMISSION_PCT
FROM
  EMPLOYEES
WHERE
  DEPARTMENT_ID = '30';

SELECT
  COUNT(*) CASE1,
  COUNT(COMMISSION_PCT) CASE2 ,
  SUM(COMMISSION_PCT) CASE3 ,
  AVG(COMMISSION_PCT) CASE4 ,
  AVG(NVL(COMMISSION_PCT,0)) CASE5 ,
  NVL(AVG(COMMISSION_PCT),0) CASE6
FROM
  EMPLOYEES
WHERE
  DEPARTMENT_ID='30';
  
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  D.DEPARTMENT_NAME
FROM
  EMPLOYEES E,
  DEPARTMENTS D
WHERE
  E.DEPARTMENT_ID    = D.DEPARTMENT_ID(+)
AND E.JOB_ID         = 'SH_CLERK'
AND D.LOCATION_ID(+) = '1500';

SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  D.DEPARTMENT_NAME,
  L.CITY
FROM
  EMPLOYEES E,
  DEPARTMENTS D,
  LOCATIONS L
WHERE
  E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND
  D.LOCATION_ID = L.LOCATION_ID
AND 
  E.JOB_ID = 'FI_ACCOUNT';


SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  D.DEPARTMENT_NAME,
  L.CITY
FROM
  EMPLOYEES E,
  DEPARTMENTS D,
  LOCATIONS L
WHERE
  E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID
ORDER BY
  D.DEPARTMENT_ID ASC;
  

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM LOCATIONS;

SELECT
  E1.LAST_NAME,
  E1.EMPLOYEE_ID,
  E2.LAST_NAME,
  E2.EMPLOYEE_ID
FROM
  EMPLOYEES E1,
  EMPLOYEES E2
WHERE
  E1.MANAGER_ID = E2.EMPLOYEE_ID(+)
ORDER BY
  E1.EMPLOYEE_ID ASC;
