SELECT * FROM TAB;

SELECT E.* , D.DNAME,D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E1.EMPNO, E1.ENAME, E2.EMPNO, E2.ENAME AS "MANAGER"
FROM EMP E1, EMP E2
WHERE EXISTS
(SELECT 1
FROM EMP E1
WHERE E1.MGR = E2.EMPNO);

SELECT E1.EMPNO, 
       E1.ENAME,
       CASE WHEN E1.MGR IS NOT NULL THEN 'MANAGER'
       END MGR, 
       E2.EMPNO, 
       E2.ENAME
FROM EMP E1, EMP E2
WHERE EXISTS
(SELECT 1
FROM EMP E1
WHERE E1.MGR = E2.EMPNO);

SELECT E1.EMPNO, 
       E1.ENAME,
       CASE WHEN E1.MGR IS NOT NULL THEN 'MANAGER'
       END MGR, 
       E2.EMPNO, 
       E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR IN (E2.EMPNO);