-- ERROR DEBUG
-- ORA-12528: TNS:리스너: 모든 해당 인스턴스가 새 접속을 차단하고 있음

-- ORACLE 리스너 상태 보기
-- CMD> LSNRCTL STATUS

-- ORACLE 리스너 서비스 시작
-- CMD> LSNRCTL START

-- ORACLE 리스너 로그 파일 경로
-- c:\app\administrator\diag\tnslsnr\roeuihyun-PC\listener\alert\log.xml

--커맨드 창에서 SQLPLUS SYS 계정으로 로그인
SQLPLUS /NOLOG

--SYSDBA 계정으로 로그인
CONN /AS SYSDBA;

-- 새로운 사용자 생성
DROP USER TEST CASCADE;
DROP TABLESPACE TEST_DATA;
ALTER SYSTEM SET DEFERRED_SEGMENT_CREATION=FALSE SCOPE=BOTH;
CREATE TABLESPACE TEST_DATA DATAFILE 'C:\APP\ADMINISTRATOR\ORADATA\ORCL\TEST_DATA.DAT' SIZE 300M AUTOEXTEND ON DEFAULT STORAGE (INITIAL 10240K NEXT 102400K MINEXTENTS 1 MAXEXTENTS UNLIMITED) ;
CREATE USER TEST IDENTIFIED BY TEST DEFAULT TABLESPACE TEST_DATA; 
GRANT CONNECT , RESOURCE TO TEST WITH ADMIN OPTION;

GRANT CONNECT TO TEST WITH ADMIN OPTION ;
GRANT DBA TO TEST WITH ADMIN OPTION ;
GRANT RESOURCE TO TEST WITH ADMIN OPTION ;
GRANT UNLIMITED TABLESPACE TO TEST WITH ADMIN OPTION ;

