DECLARE

V_NAME VARCHAR2(100);

CURSOR TEST_CURSOR IS
(SELECT 'A' AS NAME FROM DUAL UNION ALL
SELECT 'B' AS NAME FROM DUAL)
;

BEGIN

FOR I IN TEST_CURSOR LOOP 

    V_NAME := I.NAME;
    DBMS_OUTPUT.PUT_LINE('커서에서 나온 값은' || V_NAME);
    
END LOOP;

EXCEPTION 
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM || '에러발생');

END;

