--실습1

--EQUI JOIN
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.JOB_ID = 'FI_ACCOUNT' AND E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID;


--OUTER JOIN
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+) AND D.LOCATION_ID = L.LOCATION_ID(+)
ORDER BY D.DEPARTMENT_ID ASC;

--실습2

--연습문제 JOIN
SELECT E1.LAST_NAME, E1.EMPLOYEE_ID, E2.LAST_NAME, E2.EMPLOYEE_ID
  FROM EMPLOYEES E1, EMPLOYEES E2
 WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID(+)
 ORDER BY E1.EMPLOYEE_ID ASC;

--연습문제 JOIN
SELECT E1.LAST_NAME, E1.HIRE_DATE, E2.LAST_NAME, E2.HIRE_DATE
  FROM EMPLOYEES E1, EMPLOYEES E2
 WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID
   AND E1.HIRE_DATE < E2.HIRE_DATE;

--실습3

-- 2 DECODE함수 응용

SELECT RN,
       DECODE(MOD(EMPLOYEE_ID, 3), 0, EMPLOYEE_ID) AS NO1,
       DECODE(MOD(EMPLOYEE_ID, 3), 0, FIRST_NAME) AS NM1,
       DECODE(MOD(EMPLOYEE_ID, 3), 1, EMPLOYEE_ID) AS NO2,
       DECODE(MOD(EMPLOYEE_ID, 3), 1, FIRST_NAME) AS NM2,
       DECODE(MOD(EMPLOYEE_ID, 3), 2, EMPLOYEE_ID) AS NO3,
       DECODE(MOD(EMPLOYEE_ID, 3), 2, FIRST_NAME) AS NM3
  FROM (SELECT E.EMPLOYEE_ID, E.FIRST_NAME, CEIL(ROWNUM / 3) AS RN
          FROM EMPLOYEES E
         WHERE DEPARTMENT_ID = 30);

-- 3 DECODE함수 응용
SELECT RN,
       MAX(NO1) NO1,
       MAX(NM1) NM1,
       MAX(NO2) NO2,
       MAX(NM2) NM2,
       MAX(NO3) NO3,
       MAX(NM3) NM3
  FROM (SELECT RN RN,
               DECODE(MOD_RN, 1, EMPLOYEE_ID) NO1,
               DECODE(MOD_RN, 1, FIRST_NAME) NM1,
               DECODE(MOD_RN, 2, EMPLOYEE_ID) NO2,
               DECODE(MOD_RN, 2, FIRST_NAME) NM2,
               DECODE(MOD_RN, 0, EMPLOYEE_ID) NO3,
               DECODE(MOD_RN, 0, FIRST_NAME) NM3
          FROM (SELECT CEIL(ROWNUM / 3) RN,
                       MOD(ROWNUM, 3) MOD_RN,
                       EMPLOYEE_ID,
                       FIRST_NAME
                  FROM EMPLOYEES
                 WHERE DEPARTMENT_ID = 30))
 GROUP BY RN;


--실습4

WITH DEPT_COSTS AS (
    SELECT D.DEPARTMENT_NAME,
      SUM(E.SALARY) AS DEPT_TOTAL
    FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_NAME),
  AVG_COST AS (
    SELECT SUM(DEPT_TOTAL)/COUNT(*) AS DEPT_AVG
    FROM DEPT_COSTS)    
SELECT A.DEPARTMENT_NAME, A.DEPT_TOTAL
  FROM DEPT_COSTS A, AVG_COST B
  WHERE A.DEPT_TOTAL > B.DEPT_AVG
  ;

--실습5

-- 1. [서브쿼리]

SELECT EMPLOYEE_ID, LAST_NAME, SALARY
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
                          FROM EMPLOYEES
                         WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
                           AND LAST_NAME LIKE '%U%');

--2. [인라인뷰]
/*(SELECT E1.DEPARTMENT_ID, (SELECT E2.EMPLOYEE_ID || E2.LAST_NAME
FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID = E1.DEPARTMENT_ID
GROUP BY E2.EMPLOYEE_ID || E2.LAST_NAME , E2.SALARY
HAVING E2.SALARY = MAX(E1.SALARY) 
)*/

/*WITH MAX_SAL AS
 (SELECT E1.DEPARTMENT_ID, MAX(E1.SALARY) AS MAXSAL
    FROM EMPLOYEES E1
   GROUP BY E1.DEPARTMENT_ID
  HAVING E1.DEPARTMENT_ID IS NOT NULL
   ORDER BY E1.DEPARTMENT_ID),
MIN_SAL AS
 (SELECT DEPARTMENT_ID, MIN(SALARY) AS MINSAL
    FROM EMPLOYEES
   GROUP BY DEPARTMENT_ID
  HAVING DEPARTMENT_ID IS NOT NULL
   ORDER BY DEPARTMENT_ID)

SELECT M1.DEPARTMENT_ID "DID", M1.MAXSAL "SALARY", M2.DEPARTMENT_ID "DID", M2.MINSAL "SALARY"
  FROM MAX_SAL M1, MIN_SAL M2
 WHERE M1.DEPARTMENT_ID = M2.DEPARTMENT_ID;*/
 WITH SALARY AS (
     SELECT DEPARTMENT_ID
          , EMPLOYEE_ID||LAST_NAME EMP_NAME
          , SALARY
     FROM EMPLOYEES),
     MAX_SALARY AS(
     SELECT DEPARTMENT_ID
          , MAX(SALARY) MAX_SALARY
     FROM EMPLOYEES
     GROUP BY DEPARTMENT_ID),
     MIN_SALARY AS(
     SELECT DEPARTMENT_ID
          , MIN(SALARY) MIN_SALARY
     FROM EMPLOYEES
     GROUP BY DEPARTMENT_ID)
     SELECT SAL.DEPARTMENT_ID DID
          , MAX(DECODE(MAX_SALARY, SALARY, EMP_NAME)) 최대사원
          , MAX(DECODE(MAX_SALARY, SALARY, SALARY)) SALARY
          ,SAL.DEPARTMENT_ID DID
          , MAX(DECODE(MIN_SALARY, SALARY, EMP_NAME)) 최소사원
          , MAX(DECODE(MIN_SALARY, SALARY, SALARY)) SALARY
     FROM SALARY SAL
     LEFT JOIN MAX_SALARY MAX_SAL ON MAX_SAL.DEPARTMENT_ID = SAL.DEPARTMENT_ID
     LEFT JOIN MIN_SALARY MIN_SAL ON MIN_SAL.DEPARTMENT_ID = SAL.DEPARTMENT_ID
     GROUP BY SAL.DEPARTMENT_ID
     HAVING SAL.DEPARTMENT_ID IS NOT NULL
     ORDER BY DID;
  
  -- 3[스칼라 서브쿼리]
  
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       NVL((SELECT J.MAX_SALARY
             FROM JOBS J
            WHERE E.JOB_ID = J.JOB_ID
              AND J.JOB_TITLE LIKE 'SHIPPING%'),
           0) 최대급여
  FROM EMPLOYEES E
 WHERE E.DEPARTMENT_ID = 50
 ORDER BY E.EMPLOYEE_ID DESC;