-- 실습 1

-- 실습 1번
SELECT OD.ORDERID     "주문번호",
       OD.ORDERSTATUS "주문상태",
       OI.AMOUNT      "총액",
       M.NAME         "고객명",
       M.EMAIL        "EMAIL",
       I.NAME         "물품명",
       I.UNIT         "단위",
       OI.QUANTITY    "수량",
       I.MADEBY       "제조자",
       I.UNITPRICE    "금액"
  FROM MEMBER M, ITEM I, ORDERS OD, ORDER_ITEM OI
 WHERE M.MEMBERID = OD.MEMBERID
   AND OD.ORDERID = OI.ORDERID
   AND OI.ITEMID = I.ITEMID
   AND OD.ORDERDATE = '20121209'
 ORDER BY OD.ORDERID;

-- 실습 2번
SELECT DISTINCT M.NAME, M.EMAIL
  FROM MEMBER M, ORDERS OD
 WHERE M.MEMBERID = OD.MEMBERID
   AND OD.ORDERDATE LIKE '201205%'
 ORDER BY M.NAME;

SELECT M.NAME, M.EMAIL
  FROM MEMBER M
 WHERE EXISTS (SELECT 1
          FROM ORDERS OD
         WHERE M.MEMBERID = OD.MEMBERID
           AND OD.ORDERDATE LIKE '201205%');




-- 실습 2

-- 실습 3

-------------------------------------------------------------

SELECT INDEX_NAME, UNIQUENESS
FROM   ALL_INDEXES
WHERE  TABLE_NAME = 'ORDERS'
AND    OWNER = 'SH';

-------------------------------------------------------------

SELECT INDEX_NAME, COLUMN_NAME
FROM   ALL_IND_COLUMNS
WHERE  TABLE_NAME = 'ORDERS'
AND    INDEX_OWNER = 'SH' ;

-------------------------------------------------------------

SELECT C.TABLE_NAME, C.INDEX_NAME, C.COLUMN_NAME, C.COLUMN_POSITION, I.UNIQUENESS
FROM   ALL_INDEXES I, ALL_IND_COLUMNS C
WHERE  I.OWNER = C.INDEX_OWNER
AND    I.OWNER = 'SH'
AND    I.TABLE_NAME IN ('ORDERS', 'ORDER_ITEM')
AND    C.INDEX_NAME = I.INDEX_NAME
AND    C.TABLE_NAME = I.TABLE_NAME
AND    C.TABLE_OWNER = I.TABLE_OWNER
ORDER BY TABLE_NAME, INDEX_NAME, COLUMN_POSITION ;

-------------------------------------------------------------
-- INDEX 생성 이전

SELECT MEMBERID, ORDERID, ORDERSTATUS, DELIVERYNAME
  FROM ORDERS
 WHERE MEMBERID = 'BWON' ;

SELECT STATEMENT, GOAL = ALL_ROWS			7344	3585	111135
 TABLE ACCESS FULL	SH	ORDERS	7344	3585	111135

-------------------------------------------------------------
-- INDEX 생성 이후

CREATE INDEX ORD_IX02 ON ORDERS (MEMBERID) ;

SELECT MEMBERID, ORDERID, ORDERSTATUS, DELIVERYNAME
  FROM ORDERS
 WHERE MEMBERID = 'BWON' ;
 
 SELECT STATEMENT, GOAL = ALL_ROWS			1467	3585	111135
 TABLE ACCESS BY INDEX ROWID	SH	ORDERS	1467	3585	111135
  INDEX RANGE SCAN	CNSDBA	ORD_IX02	11	3585	

-- 실습 4

1. BEFORE
========================================

SELECT ROD.DELIVERYNAME
     , ROD.TOTALAMOUNT  
     , OI.ITEMID
  FROM REORDERS ROD
     , ORDER_ITEM OI
 WHERE ROD.ORDERID       = OI.ORDERID                      
   AND ROD.ORDERDATE      >= '20120501'
   AND ROD.ORDERDATE      <= '20120502'
   AND ROD.DELIVERYNAME    LIKE  '현%' ;
   
SELECT STATEMENT, GOAL = ALL_ROWS			9291	6	330
 HASH JOIN			9291	6	330
  TABLE ACCESS FULL	SH	REORDERS	7044	6	186
  TABLE ACCESS FULL	SH	ORDER_ITEM	2239	1467623	35222952

2. ACTION

========================================
ROD.ORDERID  -> TO_CHAR(ROD.ORDERID)

AND ROD.ORDERDATE      >= '20120501'
AND ROD.ORDERDATE      <= '20120502'
->
ROD.ORDERDATE BETWEEN '20120501' AND '20120502'

CREATE INDEX ORD_IDX01 ON REORDERS (DELIVERYNAME,ORDERID) ;

3. AFTER

========================================

SELECT ROD.DELIVERYNAME
     , ROD.TOTALAMOUNT  
     , OI.ITEMID
  FROM REORDERS ROD
     , ORDER_ITEM OI
 WHERE TO_CHAR(ROD.ORDERID)  = OI.ORDERID
 AND ROD.ORDERDATE BETWEEN '20120501' AND '20120502'
 AND ROD.DELIVERYNAME    LIKE  '현%' ;
 
SELECT STATEMENT, GOAL = ALL_ROWS			1543	6	330
 NESTED LOOPS					
  NESTED LOOPS			1543	6	330
   TABLE ACCESS BY INDEX ROWID	SH	REORDERS	1525	6	186
    INDEX RANGE SCAN	CNSDBA	ORD_IDX01	9	1517	
   INDEX RANGE SCAN	SH	PKORDERSERIALNO	2	1	
  TABLE ACCESS BY INDEX ROWID	SH	ORDER_ITEM	3	1	24


