SET FOREIGN_KEY_CHECKS = 0;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO tb_common_code
(MAIN_CD, SUB_CD, CODE_NM, CODE_NM_ENG, SORT_KEY, NOTE, REG_DATE, REG_ID, MOD_DATE, MOD_ID, STAT_CD) 
VALUES ('C00000', 'A', '관리자', 'admin', '1', 'NOTE',SYSDATE() , 'REG_ID', null, 'MOD_ID', 'Y');

INSERT INTO tb_auth_info
(AUTH_GROUP, MENU_ID, READ_YN, EDIT_YN, DEL_YN, REG_DATE, REG_ID, MOD_DATE, MOD_ID, STAT_CD) 
VALUES ('A', 'A0000', 'Y', 'Y', 'Y', SYSDATE(), 'REG_ID', null, null, 'Y');
INSERT INTO tb_auth_info
(AUTH_GROUP, MENU_ID, READ_YN, EDIT_YN, DEL_YN, REG_DATE, REG_ID, MOD_DATE, MOD_ID, STAT_CD) 
VALUES ('O', 'A0000', 'Y', 'Y', 'Y', SYSDATE(), 'REG_ID', null, null, 'Y');

INSERT INTO TB_USER_INFO(USER_ID,PASSWD,EMAIL,USER_NM,PHONE_NO,COMP_TEL,BASE_ADDR,DETAIL_ADDR,REG_DATE,REG_ID,STAT_CD,COMP_ID,AUTH_GROUP)VALUES
('admin',	'a1234@',	'aa@brain.com',	'관리자',	'011-2222-3333',	'02-2222-1111',	'서울특별시 금천구 가산동 60',	'904호 브레인넷',	SYSDATE(),	'admin',			'Y',	'COMP0001',	'A');
INSERT INTO TB_USER_INFO(USER_ID,PASSWD,EMAIL,USER_NM,PHONE_NO,COMP_TEL,BASE_ADDR,DETAIL_ADDR,REG_DATE,REG_ID,STAT_CD,COMP_ID,AUTH_GROUP)VALUES
('rkddn22',	'b22333@',	'bb@brain.com',	'이강우',	'010-2045-5109',	'02-3325-5454',	'서울특별시 금천구 가산동 60',	'904호 브레인넷',	SYSDATE(),	'admin',			'Y',	'COMP0002',	'O');

COMMIT;