-- ORACLE TABLE INITIAL_EXTENDS 활성화 시키기
-- 반드시 SYSDBA 계정 혹은 SYS 계정에서 실행할 것
-- DBA 권한으로 빈 테이블 누락 방지 명령어
ALTER SYSTEM SET DEFERRED_SEGMENT_CREATION=FALSE SCOPE=BOTH;

-- 테이블 이동 쿼리
SELECT 'ALTER TABLE ' || TNAME || ' MOVE;'
FROM TAB;

-- 사용자 인덱스 REBUILD
SELECT 'ALTER INDEX ' || INDEX_NAME || ' REBUILD;'
FROM USER_INDEXES;