USE ggisql;

CREATE TABLE `tb_phz86` (
  `CODE_ID` varchar(50) DEFAULT NULL,
  `CODE_NAME` varchar(50) NOT NULL,
  `CODE_NAME_EN` varchar(50) DEFAULT NULL,
  `CODE_NAME_CH` varchar(50) DEFAULT NULL,
  `CODE_PARENT_ID` varchar(50) NOT NULL,
  `SE_LANG` varchar(50) NOT NULL,
  `SEARCH_MESSAGE_ID` varchar(50) NOT NULL,
  `PARAM0_KEY` varchar(50) DEFAULT NULL,
  `PARAM1_KEY` varchar(50) DEFAULT NULL,
  `PARAM2_KEY` varchar(50) DEFAULT NULL,
  `PARAM3_KEY` varchar(50) DEFAULT NULL,
  `DEL_GB` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `tb_phz86`(`CODE_ID`,`CODE_NAME`,`CODE_NAME_EN`,`CODE_NAME_CH`,`CODE_PARENT_ID`,`SE_LANG`,`SEARCH_MESSAGE_ID`,`PARAM0_KEY`,`PARAM1_KEY`,`PARAM2_KEY`,`PARAM3_KEY`,`DEL_GB`) VALUES ('MSG_U_SKIP','메뉴','','','H_MESSAGE','KO','MESSAGE','','','','','N');
INSERT INTO `tb_phz86`(`CODE_ID`,`CODE_NAME`,`CODE_NAME_EN`,`CODE_NAME_CH`,`CODE_PARENT_ID`,`SE_LANG`,`SEARCH_MESSAGE_ID`,`PARAM0_KEY`,`PARAM1_KEY`,`PARAM2_KEY`,`PARAM3_KEY`,`DEL_GB`) VALUES ('','메뉴','','','H_MESSAGE','KO','MESSAGE','','','','','N');
