SELECT 'INSERT INTO EMP VALUES (' ||LEVEL ||')'
FROM DUAL
CONNECT BY LEVEL <100;


SELECT ROUND(DBMS_RANDOM.VALUE * LEVEL)
FROM DUAL
CONNECT BY LEVEL <100;

SELECT DBMS_RANDOM.STRING('U',10)
FROM DUAL
CONNECT BY LEVEL < 100;
