
--ENTERANCE_MASTER 99개 데이터 입력
INSERT INTO ENTERANCE_MASTER (YEAR,QUARTER,IDENTINUM,POSTGRADU_CODE,DEGREE_CODE)
(SELECT '2015' AS YEAR
       ,'1' AS QUARTER
       ,LPAD(LEVEL,4,'0') AS IDENTINUM
       ,NULL AS POSTGRADU_CODE
       ,NULL AS DEGREE_CODE
FROM DUAL
CONNECT BY LEVEL <100
);


--TYPICAL_PERFORM 198개 데이터 입력
INSERT INTO TYPICAL_PERFORM (YEAR,QUARTER,IDENTINUM,MODELSUBJECT_CODE,SCORE,ABANDONE_FLAG,STANDARD_FLAG)
(SELECT '2015' AS YEAR
       ,'1' AS QUARTER
       ,LPAD(TRUNC((LEVEL+1)/2, 0),4,'0') AS IDENTINUM
       ,LPAD(MOD(LEVEL+1,2),4,'0') AS MODELSUBJECT_CODE
       ,NULL AS SCORE
       ,NULL AS ABANDONE_FLAG
       ,NULL AS STANDARD_FLAG
FROM DUAL
CONNECT BY LEVEL <199
);

-- 실행 계획 보기
SET AUTOTRACE TRACEONLY EXPLAIN;
SET LINESIZE 300;
SET PAGESIZE 100;

SELECT COUNT(*) 
FROM ENTERANCE_MASTER 
WHERE YEAR = '2015' 
AND QUARTER = '1';
