-- ORACLE DIAMOND 그리기
SELECT LPAD(' ',12-LEVEL,' ')||LPAD('*',LEVEL,'*')||RPAD('*',LEVEL,'*') AS "DIAMOND"
FROM DUAL
CONNECT BY LEVEL < 12
UNION ALL
SELECT LPAD(' ',LEVEL,' ')||LPAD('*',12-LEVEL,'*')||RPAD('*',12-LEVEL,'*') AS "DIAMOND"
FROM DUAL
CONNECT BY LEVEL < 12