--모든 유저 확인하기
SELECT USERNAME, ACCOUNT_STATUS, LOCK_DATE FROM DBA_USERS;

--계정 잠금 해제
ALTER USER HR ACCOUNT UNLOCK;

--로그인 실패시 LOCK 걸리는 횟수
--SELECT U.*, P.*
SELECT P.PROFILE, P.RESOURCE_NAME, P.LIMIT
FROM DBA_USERS U, DBA_PROFILES P
WHERE P.PROFILE = U.PROFILE
AND   P.RESOURCE_NAME = 'FAILED_LOGIN_ATTEMPTS'
AND   USERNAME = 'SCOTT';

--로그인 실패시 LOCK 걸리는 횟수 해제
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;

SELECT * FROM SCOTT.EMP;

--LEFT OUTER JOIN
SELECT *
FROM SCOTT.EMP E LEFT OUTER JOIN SCOTT.DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT *
FROM SCOTT.EMP E , SCOTT.DEPT D
WHERE E.DEPTNO = D.DEPTNO(+);

--RIGHT OUTER JOIN
SELECT *
FROM SCOTT.EMP E RIGHT OUTER JOIN SCOTT.DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT *
FROM SCOTT.EMP E , SCOTT.DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO;

--FULL OUTER JOIN
SELECT *
FROM SCOTT.EMP E FULL OUTER JOIN SCOTT.DEPT D
ON E.DEPTNO = D.DEPTNO;

--LISTAGG( [,]) WITHIN GROUP (ORDER BY ) [OVER (PARTITION BY )]
SELECT LISTAGG(ENAME,'-') WITHIN GROUP (ORDER BY JOB)
FROM SCOTT.EMP;

--
SELECT SUBSTR(SYS_CONNECT_BY_PATH(ENAME,'-'),2)
FROM SCOTT.EMP
START WITH ENAME = 'KING'
CONNECT BY PRIOR EMPNO = MGR;